title: Sun Centered AI
description: Generative AI agentic workflow for the future of work.
theme: jekyll-theme-minimal
github:
  image: https://avatars.githubusercontent.com/u/277331392?v=4&size=64
  url: https://github.com/sunnycentered
collections:
  posts:
    output: true
    sort_by: date
    permalink: /:collection/:year/:month/:title/
